E2347. Reimplement duties controller.rb and badges controller.rb
expertiza/reimplementation-back-end pull request #39
Opened 2023-04-25 03:08 UTC by sankettangade

2023-04-27 12:22 UTC, mundra-ankur commented
> This is only a Backend Change project hence, there is no link for the hosted application. Also, we have done Swagger UI API testing for testing the API endpoints

You can still host the backend server as an API server where APIs can be tested.

2023-04-27 13:03 UTC, mundra-ankur requested changes
Hi there, it looks like there are a lot of changes required before this work can be merged. I noticed that there doesn't seem to be any testing done (API), and it appears that the guidelines may not have been followed. While I added a few review comments, there are still many other issues in other files that need to be addressed. Please make sure to follow the guidelines and make the appropriate changes.

2023-04-28 00:17 UTC, sankettangade commented on Gemfile.lock
> +  aarch64-linux
Ok. Thanks for letting us know

2023-04-28 00:17 UTC, sankettangade commented on app/controllers/api/v1/badges_controller.rb
> +  def new
Sure.

2023-04-28 00:17 UTC, sankettangade commented on app/controllers/api/v1/badges_controller.rb
> +      redirect_to redirect_to_url, notice: 'Badge was successfully created'
Modified the code as requested

2023-04-28 00:18 UTC, sankettangade commented on app/controllers/api/v1/badges_controller.rb
> +    @badges = Badge.all
Changes added as requested

2023-04-28 00:18 UTC, sankettangade commented on app/controllers/api/v1/badges_controller.rb
> +      redirect_to api_v1_badge_url(@badge), notice: 'Badge was successfully updated.'
Acknowledged

2023-04-28 00:26 UTC, sankettangade commented on app/controllers/api/v1/badges_controller.rb
> +      render :new
OK

2023-04-28 00:26 UTC, sankettangade commented on config/database.yml
> +# MySQL. Versions 5.5.8 and up are supported.
Acknowledged.

2023-04-28 00:28 UTC, sankettangade commented on app/models/duty.rb
> +  validates :name, uniqueness: { case_sensitive: false, scope: :assignment_id,
Thanks for pointing out

2026-06-29 06:20 UTC, closed without merging